# Generated by Django 4.2.2 on 2023-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowWeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/')),
                ('title', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=100)),
            ],
        ),
    ]
