# Generated by Django 4.2.2 on 2023-06-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('phone', models.IntegerField(max_length=11)),
                ('country', models.CharField(max_length=50)),
                ('findus', models.CharField(max_length=50)),
                ('comment', models.TextField()),
            ],
        ),
    ]
