# Generated by Django 4.2.2 on 2023-06-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_contactus_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='our_services')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('title1', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='our_services')),
                ('desc1', models.TextField()),
                ('image2', models.ImageField(upload_to='our_services')),
                ('desc2', models.TextField()),
                ('image3', models.ImageField(upload_to='our_services')),
                ('desc3', models.TextField()),
                ('image4', models.ImageField(upload_to='our_services')),
                ('desc4', models.TextField()),
                ('image5', models.ImageField(upload_to='our_services')),
                ('desc5', models.TextField()),
                ('image6', models.ImageField(upload_to='our_services')),
                ('desc6', models.TextField()),
            ],
        ),
    ]
