# Generated by Django 4.2.2 on 2023-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_ourservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceTitle',
            field=models.CharField(default=6.08, max_length=200),
            preserve_default=False,
        ),
    ]
