# Generated by Django 4.2.2 on 2023-06-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_service_servicetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=models.ImageField(null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image4',
            field=models.ImageField(null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image5',
            field=models.ImageField(null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image6',
            field=models.ImageField(null=True, upload_to='our_services'),
        ),
    ]
