# Generated by Django 4.2.2 on 2023-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_service_image1_alter_service_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='desc6',
            field=models.TextField(null=True),
        ),
    ]
