# Generated by Django 4.2.2 on 2023-06-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_service_desc_alter_service_desc1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='our_services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image6',
            field=models.ImageField(blank=True, default=2.1, upload_to='our_services'),
            preserve_default=False,
        ),
    ]
