# Generated by Django 4.2.2 on 2023-06-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_service_desc_alter_service_desc1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='desc6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
