# Generated by Django 4.2.2 on 2023-06-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_freetrial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrial',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
