# Generated by Django 4.2.2 on 2023-06-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_freetrial_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrial',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
