# Generated by Django 4.2.2 on 2023-06-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_pricing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pricing',
            new_name='PricingData',
        ),
    ]
