# Generated by Django 4.2.2 on 2023-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_ordernow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernow',
            name='service',
            field=models.CharField(default=1.2, max_length=200),
            preserve_default=False,
        ),
    ]
